---
title: "shiny"
author: "jesper fischer ehmsen"
date: "`r Sys.Date()`"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)

pacman::p_load(brms, tidyverse, here, cmdstanr, extraDistr, patchwork, progressr, R.utils, scales, gamlss,shiny)

```



## Distributions

```{r, warning = F, message = F, echo = F, results='hide'}
slider_params1 <- list(
  list("mu", "mu", -100, 100, 0, 1),
  list("sd", "sd", 0, 20, 1, 1)
)

slider_params2 <- list(
  list("mu_beta", "mu_beta", 0, 1, 0.5, 0.01),
  list("kappa", "kappa", 0, 50, 5, 0.5)
)

slider_params3 <- list(
  list("theta", "theta", 0, 1, 0.5, 0.01)
)
slider_params4 <- list(
  list("mean", "mean", -10, 10, 1, 0.1),
  list("std", "std", 0, 10, 1, 0.1)
  
)

slider_params5 <- list(
  list("mean_lognormal", "mean_lognormal", -10, 10, 1, 0.1),
  list("sd_lognormal", "sd_lognormal", 0, 10, 1, 0.1)
)

slider_params6 <- list(
  list("mean_gamma", "mean_gamma", 0, 100, 1, 1),
  list("sd_gamma", "sd_gamma", 0, 10, 1, 0.1)
)


slider_params7 <- list(
  list("mean_beta", "mean_beta", 0, 1, 0.5, 0.05),
  list("kappa_beta", "kappa_beta", 0, 1, 0.5, 0.05),
  list("nu_beta", "nu_beta", 0, 1, 0.5, 0.05),
  list("tau_beta", "tau_beta", 0, 1, 0.5, 0.05)
)


slider_params8 <- list(
  list("shifted_mean", "shifted_mean", -10, 10, 0, 0.1),
  list("shifted_std", "shifted_std", 0, 10, 1, 0.1),
  list("shift", "shift", 0, 1000, 0, 1))



ui <- fluidPage(
  tabsetPanel(
    tabPanel("Page 1",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params1, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot", height = "750px"))
      )
    ))),
    tabPanel("Page 2",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params2, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot2", height = "750px"))
      )
    ))),
        tabPanel("Page 3",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params3, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot3", height = "750px"))
      )
    ))),
        tabPanel("Page 4",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params4, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot4", height = "750px"))
      )
    ))),
        tabPanel("Page 5",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params5, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot5", height = "750px"))
      )
    ))),
        tabPanel("Page 6",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params6, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot6", height = "750px"))
      )
    ))),
        tabPanel("Page 7",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params7, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot7", height = "750px"))
      )
    ))),
        tabPanel("Page 8",
      sidebarLayout(
        sidebarPanel(
          lapply(slider_params8, function(p) {
            do.call(sliderInput, p)
          })
        ),
        mainPanel(
        fluidRow(
        column(12, plotOutput("plot8", height = "750px"))
      )
    )))
  )
)



server <- function(input, output) {
 normal_data = reactive({
    data3 = data.frame(x = rnorm(1000,input$mu,input$sd))
    
    return(data3)   
 })
 beta_data = reactive({
    data3 = data.frame(x = extraDistr::rprop(1000,input$kappa,input$mu_beta))
    
    return(data3)   
 })
  binominal_data = reactive({
    data3 = data.frame(x = rbinom(1000,1,input$theta))
    return(data3)   
 })
  lognormal_data = reactive({
    data3 = data.frame(x = exp(rnorm(1000,input$mean,input$std)))
    return(data3)   
 })
 
  lnorm_data = reactive({
    data3 = data.frame(x = rlnorm(1000,input$mean_lognormal,input$sd_lognormal))
    return(data3)   
 })
  
  gamma_data = reactive({
    data3 = data.frame(x = EnvStats::rgammaAlt(1000,mean = input$mean_gamma,cv = input$sd_gamma))
    return(data3)   
 })
  zoib_data = reactive({
    data3 = data.frame(x =   gamlss.dist::rBEINF(1000,mu = input$mean_beta,sigma = input$kappa_beta, nu = input$nu_beta, tau = input$tau_beta))
    return(data3)   
 })
   shifted_data = reactive({
    data3 = data.frame(x = brms::rshifted_lnorm(1000,input$shifted_mean,input$shifted_std,input$shift))
    return(data3)   
 })
  

 output$plot <- renderPlot({

     normal_data() %>% ggplot(aes(x = x)) +geom_histogram()+theme_classic()+coord_cartesian(xlim = c(input$mu-5*input$sd,input$mu+5*input$sd))+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("Normal distribution")
   
 })
 
 output$plot2 <- renderPlot({

     beta_data() %>% ggplot(aes(x = x)) +geom_histogram()+theme_classic()+coord_cartesian(xlim = c(0,1))+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("Beta distribution")
   
 })
 
 
 output$plot3 <- renderPlot({

     binominal_data() %>% ggplot(aes(x = x))+geom_histogram()+theme_classic()+coord_cartesian(xlim = c(-0.2,1.2))+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("binominal distribution")
   
 })
 
 
  output$plot4 <- renderPlot({

     lognormal_data() %>% ggplot(aes(x = x))+geom_histogram()+theme_classic()+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("exp(Normal distribution)")
   
 })
 
  
  
  output$plot5 <- renderPlot({

     lnorm_data() %>% ggplot(aes(x = x))+geom_histogram()+theme_classic()+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("lognormal distribution")
   
 })
  
    output$plot6 <- renderPlot({

     gamma_data() %>% ggplot(aes(x = x))+geom_histogram()+theme_classic()+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("Gamma distribution")
   
 })

   output$plot7 <- renderPlot({
      zoib_data() %>% ggplot(aes(x = x))+geom_histogram()+theme_classic()+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("ZIOB distribution")
   
 }) 
   
   output$plot8 <- renderPlot({
      shifted_data() %>% ggplot(aes(x = x))+geom_histogram()+theme_classic()+
       theme(legend.position = "none", text = element_text(size = 20))+ggtitle("Shifted lognormal distribution")
   
 }) 

}
```

```{r, echo = FALSE, message=F, warning=FALSE}
shinyApp(ui = ui, server = server,options = list(width = "100%", height = 800))
```